apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: consumer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: consumer
  ports:
    - port: 80
      targetPort: 9198