apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: oeyuu/producer:latest
        ports:
        - containerPort: 9196