apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: aws
  annotations:
    eks.amazonaws.com/role-arn: #hier muss noch die arn von iam role
---
apiVersion: v1
kind: pod
metadata:
  name: aws-cli
  namespace: aws
spec:
  serviceAccountName: aws-test
  containers:
    - name: aws-cli
      image: amazon/cli
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
  tolerations:
    - operator: Exists
      effect: NoSchedule
